docs_dir: docs/book
site_dir: docs/html
extra:
  project: Tutorial-101
  current_version: v1
  versions:
    - v1
nav:
  - Home: index.md
  - book:
      - Chapter 1: book/chapter-1.md
site_name: 101.dotkernel
site_description: "Beginner tutorial for using Dotkernel"
repo_url: "https://github.com/dotkernel/tutorial-101#"
plugins:
  - search