docs_dir: docs/book
site_dir: docs/html
extra:
  project: Tutorial-101
  current_version: v1
  versions:
    - v1
nav:
  - Home: index.md
  - Tutorial:
      - Introduction: v1/introduction.md
      - Chapter 1: v1/chapter-1.md
site_name: Dotkernel 101
site_description: "Beginner tutorial for using Dotkernel"
repo_url: "https://github.com/dotkernel/tutorial-101"
plugins:
  - search
